hostproject/agendjang/urls.py
from django.urls import path, include
from agendjang import views
from rest_framework import routers


# For DRF:
router = routers.DefaultRouter()
# no regex here
router.register(r'tasks', views.TaskViewSet, basename='tasks')  # basename for reverse url tags
router.register(r'dateranges', views.DateRangeViewSet, basename='dateranges')
router.register(r'events', views.EventViewSet, basename='events')

# https://docs.djangoproject.com/en/3.2/intro/tutorial03/#namespacing-url-names
app_name = 'agendjang'  # all urls here will have this namespace

urlpatterns = [
    # api root path
    path('api/', include((router.urls, 'api')), ),  # optional url namespace

    # Other urls
    path('help', views.help_view, name='help'),

    # calendars
    path('', views.CalendarView.as_view(), name='view_calendar'),
    path('js_calendar', views.JavascriptCalendarView.as_view(), name='view_js_calendar'),

    # Tasks
    path('create_task', views.TaskCreate.as_view(), name='create_task'),
    path('update_task/<int:pk>', views.TaskUpdate.as_view(), name='update_task'),

    # Tags
    path('create_tag', views.TagCreate.as_view(), name='create_tag'),
    path('update_tag/<int:pk>', views.TagUpdate.as_view(), name='update_tag'),

]

hostproject/hostproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('agendjang.urls')),
]

hostproject/agendjang/models.py
from django.db import models


class TaskManager(models.Manager):
    """Overrides the default manager all() method in order to only return results that are not archived"""

    def all(self):
        return self.filter(archive=False)


class Task(models.Model):
    """
    Procrastinated task
    """
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    done = models.BooleanField(default=False)
    archive = models.BooleanField(default=False)
    points = models.IntegerField(default=1)

    many_tags = models.ManyToManyField('Tag', blank=True)

    objects = TaskManager()

    def __str__(self):
        return f"Task {self.name}"


class DateRange(models.Model):
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    task = models.ForeignKey(Task, on_delete=models.CASCADE)  # when task is deleted, linked DateRange is removed too

    def __str__(self):
        return f"DateRange, {self.start_date}"

    def __add__(self, other):
        return DateRange(start_date=self.start_date + other, end_date=self.end_date + other)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save(force_insert, force_update, using, update_fields)
        return self  # allow to chain the save method


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"Tag {self.name}"

hostproject/agendjang/forms.py
from django import forms
from agendjang.models import Task, Tag


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'

hostproject/agendjang/views.py
from django.shortcuts import HttpResponse
from django.template import loader
from django.views.generic import TemplateView, ListView, CreateView, UpdateView
from django.utils import timezone
from django.urls import reverse_lazy

from agendjang.models import Task, DateRange, Tag
from agendjang.forms import TaskForm, TagForm
from agendjang.serializers import TaskSerializer, DateRangeSerializer, EventSerializer

from rest_framework import viewsets
from rest_framework.response import Response

from markdown import markdown

from datetime import timedelta, datetime


#######
# API #
#######


class TaskViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer


class DateRangeViewSet(viewsets.ModelViewSet):
    queryset = DateRange.objects.all()
    serializer_class = DateRangeSerializer


class EventViewSet(viewsets.ViewSet):
    def list(self, request):
        """With calendar month view, 'start' and 'end' params are dates,
         but in week and day views they are datetime.
         We parse only the date part of the date, because reducing results with hour precision is useless"""
        start = self.request.query_params.get('start')
        end = self.request.query_params.get('end')

        # parse the first part of the string, containing only the date (ignore time string)
        start = timezone.make_aware(datetime.strptime(start[0:10], '%Y-%m-%d'))
        end = timezone.make_aware(datetime.strptime(end[0:10], '%Y-%m-%d'))

        qs = []

        for task in Task.objects.all():
            for daterange in task.daterange_set.filter(start_date__gte=start, end_date__lte=end):
                qs.append({
                    'taskId': task.id,
                    'id': daterange.pk,
                    'title': task.name,
                    'start': daterange.start_date,
                    'end': daterange.end_date,
                    'allDay': True if daterange.end_date - daterange.start_date == timedelta(hours=24) else False,
                    'color': 'red' if (not task.done and timezone.now() > daterange.end_date) else 'green',
                })

        serializer = EventSerializer(qs, many=True)
        return Response(serializer.data)


#############
# Templates #
#############

def help_view(request):
    """Read a markdown help file and convert it to html"""
    return HttpResponse(markdown(loader.render_to_string('agendjang/help.md')))


class TaskCreate(CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('agendjang:view_calendar')


class TaskUpdate(UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('agendjang:view_calendar')


class TagCreate(CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy('agendjang:view_calendar')


class TagUpdate(UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy('agendjang:view_calendar')


class CalendarView(TemplateView):
    template_name = 'agendjang/calendar.html'

    def get_context_data(self, **kwargs):  # adds the tag_list template tag, along object_list
        ctx = super().get_context_data(**kwargs)
        ctx['tag_list'] = Tag.objects.all()
        return ctx


class JavascriptCalendarView(ListView):
    model = Task  # ListView because i export TaskList in the js calendar as django tags
    template_name = 'agendjang/js_calendar.js'
    content_type = 'text/javascript'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['tag_list'] = Tag.objects.all()
        return ctx

hostproject/agendjang/templates/agendjang/calendar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Agendjang</title>
    {% load static %}
    <link rel='stylesheet' href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.6.1/fullcalendar.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel='stylesheet' href="{% static 'css/impose_ton_style.css' %}" />

    <script src="//code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.6.1/fullcalendar.js"></script>

    <!--js with django tags, in a separate view-->
    <script src="{% url 'agendjang:view_js_calendar' %}"></script>

</head>

<footer>
    <div id='help_page' title="Help Page" style="display: none;"></div>
    <button id="btn_help" type="button"
            onclick="loadDialog('#help_page', 'help')">Help</button>
</footer>

<body>
    <!--display none to hide when page loaded; called by eventCLick in js_calendar-->
    <div id='task_dialog' title="Edit task" style="display: none;"></div>

    <div id='calendar'></div>

    <!--loads dialog into a hidden div with content from another url-->
    <script>
        function loadDialog(domId, relUrl) {
            $(domId).load(relUrl);
            $(domId).dialog({width: 'auto'});
        }
    </script>

    <div id=tags>

        <div id='create_tag_dialog' title="Create tag" style="display: none;"></div>
        <button id="btn_create_tag" type="button"
                onclick="loadDialog('#create_tag_dialog', 'create_tag')">New tag</button>

    {% for tag in tag_list %}
        <div id="{{ tag.name }}" class="accord" >

            <h3>{{ tag.name }}</h3>

            <div>
            <!--necessary div to contain tasks into accordion-->
                <div id='modify_tag_dialog' title="Modify tag" style="display: none;"></div>
                <button id="btn_modify_tag" type="button"
                        onclick="loadDialog('#modify_tag_dialog', 'update_tag/{{tag.pk}}')">Modify tag</button>

            {% for task in tag.task_set.all %}
                {% if not task.done %}
                    <!--several classes split with spaces-->
                    <div class="task_div {{ task.pk }}"> {{ task.name }}

                        <div id='edit_task_dialog' title="Edit task" style="display: none;"></div>
                            <button id="btn_edit_task" type="button"
                                    onclick="loadDialog('#edit_task_dialog', 'update_task/{{task.pk}}' )">EDIT</button>
                    </div>

                    <script>
                        $('.{{ task.pk }}').data('event', {
                            title: '{{ task.name }}',
                            taskId: '{{ task.pk }}',
                            stick: false});
                    </script>
                {% endif %}

            {% endfor %}

            </div>
        </div>
    {% endfor %}

        <!--makes tasks draggable-->
         <script>
             $('.task_div').draggable({
                 revert: true,      // immediately snap back to original position
                 revertDuration: 8,  // time to snap back
                 helper: "clone",  // correct zindex of draggable element, dunno how
             });
         </script>

    </div>

</body>


</html>

hostproject/agendjang/templates/agendjang/tag_form.html
<form action="{{ request.path }}" method="post" enctype="multipart/form-data">
    <!--request.path because when called from a different url-->
    <table>
        {% csrf_token %}
        {{ form.as_table }}
    </table>

    <input type="submit" value="Submit" />
</form>

hostproject/agendjang/templates/agendjang/task_form.html
<form action="{{ request.path }}" method="post" enctype="multipart/form-data">
    <!--request.path because when called from a different url-->
    <table>
        {% csrf_token %}
        {{ form.as_table }}
    </table>

    <input id="task_input" type="submit" value="Submit" />
</form>